USER $USER
WORKDIR $HOME_DIR

RUN echo "export PATH=$CMD_LINE_BINARIES:$PLATFORM_TOOLS_BINARIES:$ANDROID_TOOLS_BINARIES:\$PATH" >> .zshrc
RUN echo 'export ANDROID_HOME=$HOME/android_sdk\n\
export ANDROID_SDK_ROOT=$HOME/$ANDROID_SDK_DIR \n\
export ANDROID_USER_HOME=$HOME/.android' >> .zshrc